### ISSUE TITLE
Hyperlink to `existing deep link` points to a local link

### ISSUE THREAD

**Issue by ChrisGuzman** [google/search-samples#10]
On [step 8](http://search-codelabs.appspot.com/codelabs/app-indexing#8) towards the bottom of the page, there is the text "There should be an existing deep link in the app for each API call."

If you click on the the link `deep link`, it directs you to the Uri `http://localhost:22080/app-indexing/webmasters/app`

**Comment by HunjaeJung** [comment]
+1

**Comment by zayna-shahzad** [comment]
Looks like this has since been fixed. Closing.
