### ISSUE TITLE
Missing .gitignore means unwanted files

### ISSUE THREAD

**Issue by rock3r** [google/search-samples#12]
I'm doing the App Indexing codelab and I've noticed that all the sample code here contains `local.properties` files... You get warning from AS when importing the code because of course the SDK location is not the one defined in that file (points to some guy's Linux home folder). The repo also contains some `.gradle` and `.idea` folders and `.iml` files than shouldn't be there. Please clean up the repo.

**Comment by devunwired** [comment]
Hopefully a PR will help speed along the process ;)
