### ISSUE TITLE
Google Codelab - import wrong in documentation

### ISSUE THREAD

**Issue by Shanannigans** [google/search-samples#17]
In the documentation ( http://search-codelabs.appspot.com/codelabs/voice-search#6 ), there is an old import of the play-services-appindexing library, namely com.google.android.gms:play-services-appindexing:6.5.87

The app itself uses methods for appIndexing, which are not available in this method, but in     com.google.android.gms:play-services-appindexing:7.0.0, please update the codelab example accordingly.

**Comment by zayna-shahzad** [comment]
http://search-codelabs.appspot.com has been deprecated in favor of https://codelabs.developers.google.com
While the codelabs on http://search-codelabs.appspot.com are still accessible, they are not actively being maintained and will be removed shortly.
Codelabs from https://codelabs.developers.google.com are maintained and updated. Any feedback on those should be reported with the feedback links found in the respective codelab itself. 
Thank you :)
