### ISSUE TITLE
Add GitHub repo description

### ISSUE THREAD

**Issue by dandv** [google/search-samples#3]
Would be nice to see it in the list at https://github.com/google

**Comment by dandv** [comment]
Ping @cramforce.

**Comment by cramforce** [comment]
I don't completely follow why I was mentioned here :) How can I help?

**Comment by dandv** [comment]
Hey Malte,

You were one fellow Googler I knew to be active on GitHub and probably connected with someone with access to this repo, since it seems @narphorium hasn't had time to maintain it.

**Comment by cramforce** [comment]
You could email github-requests@
