### ISSUE TITLE
Update the sample to use com.google.android.gms:play-services-appindexing:6.5.87

### ISSUE THREAD

**Issue by wjarek** [google/search-samples#6]
Context: http://android-developers.blogspot.com/2014/12/google-play-services-and-dex-method.html

**Comment by zayna-shahzad** [comment]
Drive-by cleanup...
Since this issue is from 2014, and the current appindexing sample in this repo is using `com.google.android.gms:play-services-appindexing:7.0.0` > `6.5.x`, I am going to close this out. Please feel free to reopen this if you think it is by mistake.
